import {
  mysqlTable,
  varchar,
  int,
  double,
  boolean,
  text,
  index,
  uniqueIndex,
} from 'drizzle-orm/mysql-core'

export const profiles = mysqlTable(
  'profiles',
  {
    id: varchar('id', { length: 191 }).primaryKey(),
    account: varchar('account', { length: 191 }).notNull(),
    password_hash: varchar('password_hash', { length: 255 }).notNull().default(''),
    nickname: varchar('nickname', { length: 80 }),
    gender: varchar('gender', { length: 32 }),
    age: int('age'),
    appearance: varchar('appearance', { length: 64 }),
    identity: varchar('identity', { length: 64 }),
    location: varchar('location', { length: 64 }),
    grade: varchar('grade', { length: 64 }),
    bio: text('bio'),
    avatar_url: varchar('avatar_url', { length: 1024 }),
    contact_visibility_limit: int('contact_visibility_limit').notNull().default(0),
    balance: double('balance').notNull().default(0),
    is_verified: boolean('is_verified').notNull().default(false),
    is_profile_complete: boolean('is_profile_complete').notNull().default(false),
    app_role: varchar('app_role', { length: 32 }).notNull().default('user'),
    campus_available_balance: double('campus_available_balance').notNull().default(0),
    campus_pending_balance: double('campus_pending_balance').notNull().default(0),
    campus_settlement_applying_amount: double('campus_settlement_applying_amount').notNull().default(0),
    campus_settled_total: double('campus_settled_total').notNull().default(0),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    updated_at: varchar('updated_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    uniqueIndex('idx_profiles_account').on(table.account),
    index('idx_profiles_gender').on(table.gender),
    index('idx_profiles_age').on(table.age),
    index('idx_profiles_identity').on(table.identity),
    index('idx_profiles_appearance').on(table.appearance),
  ],
)

export const contactPool = mysqlTable(
  'contact_pool',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    user_id: varchar('user_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    wechat: varchar('wechat', { length: 191 }),
    qq: varchar('qq', { length: 191 }),
    phone: varchar('phone', { length: 191 }),
    is_active: boolean('is_active').notNull().default(true),
    drawn_count: int('drawn_count').notNull().default(0),
    max_drawn_count: int('max_drawn_count').notNull().default(0),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    updated_at: varchar('updated_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    uniqueIndex('idx_contact_pool_user_id').on(table.user_id),
    index('idx_contact_pool_active').on(table.is_active),
  ],
)

export const drawHistory = mysqlTable(
  'draw_history',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    drawer_id: varchar('drawer_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    target_id: varchar('target_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    amount: double('amount').notNull().default(0),
    status: varchar('status', { length: 64 }).notNull().default('PENDING_PAYMENT'),
    contact_wechat: varchar('contact_wechat', { length: 191 }),
    contact_qq: varchar('contact_qq', { length: 191 }),
    contact_phone: varchar('contact_phone', { length: 191 }),
    note: varchar('note', { length: 255 }),
    is_deleted: boolean('is_deleted').notNull().default(false),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    index('idx_draw_history_drawer').on(table.drawer_id),
    index('idx_draw_history_created').on(table.created_at),
  ],
)

export const emailVerificationCodes = mysqlTable(
  'email_verification_codes',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    email: varchar('email', { length: 191 }).notNull(),
    purpose: varchar('purpose', { length: 64 }).notNull(),
    code_hash: varchar('code_hash', { length: 255 }).notNull(),
    expires_at: varchar('expires_at', { length: 64 }).notNull(),
    sent_at: varchar('sent_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    consumed_at: varchar('consumed_at', { length: 64 }),
    attempt_count: int('attempt_count').notNull().default(0),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    updated_at: varchar('updated_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    uniqueIndex('idx_email_verification_email_purpose').on(table.email, table.purpose),
    index('idx_email_verification_email').on(table.email),
  ],
)

export const campusExpressOrders = mysqlTable(
  'campus_express_orders',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    order_no: varchar('order_no', { length: 64 }).notNull(),
    user_id: varchar('user_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    runner_id: varchar('runner_id', { length: 191 }),
    small_count: int('small_count').notNull().default(0),
    medium_count: int('medium_count').notNull().default(0),
    large_count: int('large_count').notNull().default(0),
    xlarge_count: int('xlarge_count').notNull().default(0),
    total_count: int('total_count').notNull().default(0),
    pickup_station: varchar('pickup_station', { length: 255 }).notNull(),
    pickup_codes: text('pickup_codes').notNull(),
    delivery_building: varchar('delivery_building', { length: 255 }).notNull(),
    delivery_address: varchar('delivery_address', { length: 255 }).notNull(),
    expected_time: varchar('expected_time', { length: 255 }).notNull(),
    remark: text('remark'),
    order_amount: double('order_amount').notNull(),
    platform_fee: double('platform_fee').notNull(),
    runner_income: double('runner_income').notNull(),
    pay_type: varchar('pay_type', { length: 32 }),
    status: varchar('status', { length: 64 }).notNull().default('PENDING_PAYMENT'),
    paid_at: varchar('paid_at', { length: 64 }),
    accepted_at: varchar('accepted_at', { length: 64 }),
    picked_up_at: varchar('picked_up_at', { length: 64 }),
    delivered_at: varchar('delivered_at', { length: 64 }),
    confirmed_at: varchar('confirmed_at', { length: 64 }),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    updated_at: varchar('updated_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    uniqueIndex('idx_express_order_no').on(table.order_no),
    index('idx_express_user_id').on(table.user_id),
    index('idx_express_runner_id').on(table.runner_id),
    index('idx_express_status').on(table.status),
  ],
)

export const campusBookPosts = mysqlTable(
  'campus_book_posts',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    seller_id: varchar('seller_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    title: varchar('title', { length: 255 }).notNull(),
    category: varchar('category', { length: 255 }).notNull(),
    isbn: varchar('isbn', { length: 64 }),
    condition_level: varchar('condition_level', { length: 64 }).notNull(),
    sale_price: double('sale_price').notNull(),
    platform_fee: double('platform_fee').notNull().default(2),
    seller_income: double('seller_income').notNull(),
    description: text('description'),
    shelf_status: varchar('shelf_status', { length: 64 }).notNull().default('ON_SALE'),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    updated_at: varchar('updated_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    index('idx_book_posts_seller_id').on(table.seller_id),
    index('idx_book_posts_shelf_status').on(table.shelf_status),
  ],
)

export const campusBookOrders = mysqlTable(
  'campus_book_orders',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    order_no: varchar('order_no', { length: 64 }).notNull(),
    book_id: varchar('book_id', { length: 191 }).notNull().references(() => campusBookPosts.id, { onDelete: 'cascade' }),
    book_title: varchar('book_title', { length: 255 }).notNull(),
    buyer_id: varchar('buyer_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    seller_id: varchar('seller_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    sale_price: double('sale_price').notNull(),
    platform_fee: double('platform_fee').notNull(),
    seller_income: double('seller_income').notNull(),
    delivery_building: varchar('delivery_building', { length: 255 }).notNull(),
    pay_type: varchar('pay_type', { length: 32 }),
    status: varchar('status', { length: 64 }).notNull().default('PENDING_PAYMENT'),
    paid_at: varchar('paid_at', { length: 64 }),
    delivered_at: varchar('delivered_at', { length: 64 }),
    received_at: varchar('received_at', { length: 64 }),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    updated_at: varchar('updated_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    uniqueIndex('idx_book_order_no').on(table.order_no),
    index('idx_book_orders_buyer_id').on(table.buyer_id),
    index('idx_book_orders_seller_id').on(table.seller_id),
    index('idx_book_orders_status').on(table.status),
  ],
)

export const campusPaymentRecords = mysqlTable(
  'campus_payment_records',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    out_trade_no: varchar('out_trade_no', { length: 64 }).notNull(),
    biz_type: varchar('biz_type', { length: 64 }).notNull(),
    biz_id: varchar('biz_id', { length: 191 }).notNull(),
    user_id: varchar('user_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    amount: double('amount').notNull(),
    pay_type: varchar('pay_type', { length: 32 }),
    status: varchar('status', { length: 64 }).notNull().default('CREATED'),
    trade_status: varchar('trade_status', { length: 64 }),
    gateway_trade_no: varchar('gateway_trade_no', { length: 255 }),
    gateway_order_id: varchar('gateway_order_id', { length: 255 }),
    pay_url: text('pay_url'),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    updated_at: varchar('updated_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    uniqueIndex('idx_payment_out_trade_no').on(table.out_trade_no),
    index('idx_payment_user_id').on(table.user_id),
  ],
)

export const campusSettlementApplications = mysqlTable(
  'campus_settlement_applications',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    application_no: varchar('application_no', { length: 64 }).notNull(),
    user_id: varchar('user_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    amount: double('amount').notNull(),
    status: varchar('status', { length: 64 }).notNull().default('PENDING'),
    user_role: varchar('user_role', { length: 32 }).notNull().default('user'),
    payee_qr_code: varchar('payee_qr_code', { length: 1024 }),
    note: text('note'),
    transfer_ref: varchar('transfer_ref', { length: 255 }),
    handled_by: varchar('handled_by', { length: 191 }),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
    updated_at: varchar('updated_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    uniqueIndex('idx_settlement_application_no').on(table.application_no),
    index('idx_settlement_user_id').on(table.user_id),
    index('idx_settlement_status').on(table.status),
  ],
)

export const campusBalanceLogs = mysqlTable(
  'campus_balance_logs',
  {
    id: varchar('id', { length: 191 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
    user_id: varchar('user_id', { length: 191 }).notNull().references(() => profiles.id, { onDelete: 'cascade' }),
    biz_type: varchar('biz_type', { length: 64 }).notNull(),
    biz_id: varchar('biz_id', { length: 191 }).notNull(),
    change_type: varchar('change_type', { length: 64 }).notNull(),
    amount: double('amount').notNull(),
    before_available: double('before_available').notNull().default(0),
    after_available: double('after_available').notNull().default(0),
    before_pending: double('before_pending').notNull().default(0),
    after_pending: double('after_pending').notNull().default(0),
    remark: text('remark'),
    created_at: varchar('created_at', { length: 64 }).notNull().$defaultFn(() => new Date().toISOString()),
  },
  (table) => [
    index('idx_balance_logs_user_id').on(table.user_id),
  ],
)
